export const ADD_USER = 'ADD_USER'
export const ADD_ASSIGNEES = 'ADD_ASSIGNEES'
export const SET_ASSIGNEE = 'SET_ASSIGNEE'
export const ADD_MY_WINDOW = 'ADD_MY_WINDOW'
export const COMPLETE_ASSIGNEE = 'COMPLETE_ASSIGNEE'
export const TOGGLE_ADJECTIVE = 'TOGGLE_ADJECTIVE'

